source 'http://rubygems.org'
gem 'sinatra'
gem 'activerecord', '~> 3.2.8'
#gem 'activerecord-jdbcpostgresql-adapter'
gem 'pg'
#gem 'ruby-debug19', :require => 'ruby-debug'
gem 'shoulda'
gem 'rest-client'
gem 'puma'
gem 'rack-test'
gem 'rake'
